test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/test_64_256/lr_64
      root_path_2: ./load/test_64_256/hr_256
      cache: bin
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}